# ------------------------------------------------------------------
# PREDICTIVE MAINTENANCE CONFIGURATION
# ------------------------------------------------------------------

data:
  train_file: 'CMaps/test_FD001.txt'      # Location of Training File

parameters:
  healthy_threshold: 100
  warning_threshold: 30
  critical_threshold: 15
  critical_RUL: 20

anomaly_detection:
  healthy_percentage: 0.80      # Since this dataset is guaranteed to end at the exact moment of engine failure, we train the front 80% as normal
  contamination: 0.01           # Assume 1% of the data fed is bad

features:
  window_size: 10   # Rolling Window Size
  correlation_threshold: 0.05     # How strongly a sensor must correlate with RUL. 0.0 = Keep all and 1.0 = Keep only perfect
  whitelist:        # Name all Sensors to protect from Feature Selection removal
    - "s_2"
    - "s_14"
    - "s_7"

  sensor_names:     # Name all Sensors here
    - "s_1"
    - "s_2"
    - "s_3"
    - "s_4"
    - "s_5"
    - "s_6"
    - "s_7"
    - "s_8"
    - "s_9"
    - "s_10"
    - "s_11"
    - "s_12"
    - "s_13"
    - "s_14"
    - "s_15"
    - "s_16"
    - "s_17"
    - "s_18"
    - "s_19"
    - "s_20"
    - "s_21"

training:
  test_size: 0.2          # Portion of data saved for testing the model
  random_state: 42        # RNG seed
  n_estimators: 100       # Number of Regression Tree "Voters"

output:
  model_filename: "pdm_model_v1.pkl"
  results_filename: "training_metrics.txt"